### ISSUE TITLE
Doesn't account for mods that lower max health

### ISSUE THREAD

**Issue by SimonMeskens** [AwwShoot/saturation-fixer#1]
I don't know the exact solution for this, but maybe the 5 hearts thing shouldn't be hard-coded. I have a pack where I want to start the player off with 3 hearts, so I can't really use this mod, but I want to. Maybe it should just be a 50% check on the current max health? Not sure.

**Comment by AwwShoot** [comment]
Do you mean max hunger? There are no hardcoded values relating to health.

**Comment by SimonMeskens** [comment]
Never mind this issue, I had been sitting in the sun all day drinking wine and what I wrote above is pure gibberish. Thanks for the great mod :)
